sudo: required
services: 
  - docker


before_install:
  - docker build -t chinnakrit/docker-react -f Dockerfile.dev .


script:
  - docker run chinnakrit/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-131565378728"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KRY
  secret_access_key: $AWS_SECRET_KRY
